# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b8ce0a82aa2446bfe27a7f14d23da2a"
name = "seel-extensions"
handle = "seel-extensions"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "test-for-extensibility.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_products,write_pixels,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
